-- 코드를 작성해주세요
# BASS와 SNAPPER의 수
# 컬럼명 'FISH_COUNT'
SELECT COUNT(*) AS 'FISH_COUNT'
FROM FISH_INFO AS A
LEFT JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.FISH_NAME = 'BASS' OR B.FISH_NAME = 'SNAPPER'