-- 코드를 입력하세요
# 성분 타입, 성분 타입에 대한 아이스크림의 총주문량 조회
# 총주문량이 작은 순서대로 정렬

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF LEFT JOIN ICECREAM_INFO
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC